"""Argo CronWorkflow manifest generation for scheduled scenario runs.

The app does not talk to the Argo API. It generates a CronWorkflow YAML that
an operator commits to their manifests repo. On its schedule, Argo POSTs the
token-authed ``/scenarios/<id>/scheduled-run`` endpoint; the app runs the
scenario and logs a structured summary to stdout, which Argo captures — that
log line is the notification surface.
"""
import re

from config import Config

_CRON_FIELD = r'[\d*/,\-?LW#]+'
_CRON_RE = re.compile(r'^\s*' + r'\s+'.join([_CRON_FIELD] * 5) + r'\s*$')


def validate_cron(schedule: str) -> str:
    """Return the trimmed cron string, or raise ValueError if it isn't a
    plausible 5-field cron expression."""
    s = (schedule or '').strip()
    if not s:
        raise ValueError('A cron schedule is required (5 fields, e.g. "0 6 * * 0").')
    if not _CRON_RE.match(s):
        raise ValueError(
            f'"{s}" is not a valid 5-field cron expression. '
            f'Example: "0 6 * * 0" = 6:00 every Sunday.'
        )
    return s


def _slug(name: str) -> str:
    """Lowercase, dash-separated, DNS-safe slug for the workflow name."""
    slug = re.sub(r'[^a-z0-9]+', '-', (name or '').lower()).strip('-')
    return slug or 'scenario'


def generate_cronworkflow(scenario_id: int, scenario_name: str, schedule: str, *,
                          base_url: str = None, namespace: str = None,
                          timezone: str = None, secret_name: str = None,
                          secret_key: str = None, image: str = None) -> str:
    """Render an Argo CronWorkflow that triggers a scenario on a schedule.

    The workflow curls the scheduled-run endpoint with the scheduler token
    pulled from a K8s secret. ``curl -f`` makes a non-2xx response fail the
    workflow, so a failed/partial run surfaces in the Argo UI; the app's own
    structured stdout log carries the per-step detail.

    namespace/timezone/secret_name/secret_key/image default to Config.ARGO_*
    (Doane-specific values, but env-overridable — Higher-Ed-agnostic posture,
    same as the CLI tab's defaults). Resolved here rather than as literal
    parameter defaults so a runtime Config change (or a test monkeypatch)
    takes effect without needing this module reloaded.
    """
    schedule = validate_cron(schedule)
    namespace = namespace or Config.ARGO_NAMESPACE
    timezone = timezone or Config.ARGO_TIMEZONE
    secret_name = secret_name or Config.ARGO_SECRET_NAME
    secret_key = secret_key or Config.ARGO_SECRET_KEY
    image = image or Config.ARGO_IMAGE
    base = (base_url or Config.PUBLIC_BASE_URL).rstrip('/')
    url = f'{base}/scenarios/{scenario_id}/scheduled-run'
    # K8s object names are DNS-1123: max 253, but keep it short and readable.
    wf_name = f'sf-mc-scenario-{scenario_id}-{_slug(scenario_name)}'[:52].rstrip('-')

    return f"""# Generated by SF Mission Control — Argo CronWorkflow for scenario {scenario_id}
# Commit this to your manifests repo. The scheduler token must exist in the
# '{secret_name}' secret under key '{secret_key}' (same secret the app uses).
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: {wf_name}
  namespace: {namespace}
spec:
  schedule: "{schedule}"
  timezone: "{timezone}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  workflowSpec:
    entrypoint: trigger
    templates:
      - name: trigger
        container:
          image: {image}
          command: ["sh", "-c"]
          args:
            - >-
              curl -fsS -X POST
              -H "X-MC-Scheduler-Token: $MC_TOKEN"
              "{url}"
          env:
            - name: MC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {secret_name}
                  key: {secret_key}
"""
